In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [4]:
df=pd.read_csv(r'C:\Users\Shasaank\Work\house price predictor\data\processed\Housing_cleaned.csv')
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,0,0
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,0,0
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,1,0
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,0,0
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,0,0

Train Test Split

In [16]:
X=df.drop('price',axis=1)
Y=df['price']

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

Linear Regression Model Training

In [19]:
LR_model=LinearRegression()
LR_model.fit(X_train,Y_train)
Y_pred_LR=LR_model.predict(X_test)

Randon Forest Model Training

In [28]:
RF_model=RandomForestRegressor(n_estimators=100,random_state=42)
RF_model.fit(X_train,Y_train)
Y_pred_RF=RF_model.predict(X_test)

Metrics

In [29]:
def evaluate_model(y_true, y_pred):
    mae= mean_absolute_error(y_true,y_pred)

    mse= mean_squared_error(y_true,y_pred)
    rmse= np.sqrt(mse)

    r2= r2_score(y_true,y_pred)

    return mae,rmse,r2

In [35]:
LR_MAE, LR_RMSE, LR_R2 = evaluate_model(Y_test, Y_pred_LR)
print(f"Linear Regression Model Evaluation:\nMAE: {MAE}\nRMSE: {RMSE}\nR2 Score: {R2}")

Linear Regression Model Evaluation:
MAE: 1022560.0527522935
RMSE: 1401496.8425384816
R2 Score: 0.6114024924156645

In [36]:
RF_MAE, RF_RMSE, RF_R2 = evaluate_model(Y_test, Y_pred_RF)
print(f"Random Forest Model Evaluation:\nMAE: {MAE}\nRMSE: {RMSE}\nR2 Score: {R2}")

Random Forest Model Evaluation:
MAE: 1022560.0527522935
RMSE: 1401496.8425384816
R2 Score: 0.6114024924156645

Comparision

In [37]:
comp_df=pd.DataFrame()
comp_df=comp_df.assign(
    model=['Linear Regression','Random Forest'],
    MAE=[LR_MAE,RF_MAE],
    RMSE=[LR_RMSE,RF_RMSE],
    R2=[LR_R2,RF_R2]
)

comp_df.to_csv(r'C:\Users\Shasaank\Work\house price predictor\data\processed\model_comparison.csv',index=False)
comp_df.head()

               model           MAE          RMSE        R2
0  Linear Regression  9.700434e+05  1.324507e+06  0.652924
1      Random Forest  1.022560e+06  1.401497e+06  0.611402